---
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyverse)
library(DBI)
library(glue)

user_selected <- "dgco100@mininter.gob.pe"

start_date <- lubridate::today() - lubridate::weeks(8)
end_date <- lubridate::today()

theme_set(theme_light())
```


```{r}
con <- dbConnect(
    drv = RMariaDB::MariaDB(),
    user = Sys.getenv("DB_USER"),
    password = Sys.getenv("DB_SECRET"),
    dbname = Sys.getenv("DB_NAME"),
    host = Sys.getenv("DB_HOST"),
    port = Sys.getenv("DB_PORT")
)
```

```{r}
group_selected <- dbGetQuery(con, "SELECT group_id, count(group_id) AS n FROM tasks GROUP BY group_id") |> 
    filter(n == max(n)) |> 
    pull(group_id)

group_info <- dbGetQuery(con, "SELECT * FROM groups WHERE group_id = '{group_selected}'" |> glue()) |> as.list()
```

```{r}
user_info <- dbGetQuery(con, "SELECT * FROM users WHERE email = '{user_selected}'" |> glue()) |> as.list()
```


## Información de usuario

- Grupo seleccionado: `r group_info$group_title`
- Usuario seleccionado: `r glue("{user_info$name} {user_info$last_name}")`

## Tareas

```{r}
st_tasks <- glue_sql(
    "SELECT * 
    FROM tasks
    WHERE 
        group_id = {group_selected} AND
        assignee = {user_info$user_id}",
    .con = con
)

tasks <- dbGetQuery(con, st_tasks)
```

```{r}
task_per_day <- tasks |> 
    mutate(
        fecha = as.Date(time_creation)
    ) |> 
    # group_by(fecha) |> 
    summarise(
        n = n(),
        .by = fecha
    ) |> 
    arrange(fecha) |> 
    mutate(
        cummulative = cumsum(n)
    )
```

### Tareas agregadas por fecha

```{r}
task_per_day |>
    ggplot(aes(fecha, n)) +
    geom_line() +
    geom_point()
```

### Acumulado de tareas agregadas por fecha

```{r}
task_per_day |>
    ggplot(aes(fecha, cummulative)) +
    geom_line() +
    geom_point()
```

### Cantidad de tareas activas

```{r}
tasks |> 
    mutate(
        status = fct(status_current) |> fct_other(keep = "Archivado", other_level = "Activo")
    ) |> 
    count(status, .drop = FALSE) |> 
    ggplot(aes(n, status)) +
    geom_col() +
    geom_label(aes(label = n), hjust = "inward")
```

### Estado de tareas activas

```{r}
statuses <- c("Pendiente", "En proceso", "Pausado", "En revisión", "Observado", "Terminado")

tasks |> 
    filter(status_current != "Archivado") |> 
    mutate(status_current = fct(status_current, statuses)) |> 
    count(status_current, .drop = FALSE) |> 
    ggplot(aes(n, status_current)) +
    geom_col() +
    geom_label(aes(label = n), hjust = "inward")
```


```{r}
all_dates <- seq(min(task_per_day$fecha), max(task_per_day$fecha), by = "days")

st_progress <- glue_sql("SELECT * FROM progress WHERE task_id IN ({tasks$task_id*})", .con = con)

progress <- dbGetQuery(con, st_progress)
```

### Evolución del estado de las tareas asignadas

```{r}
progress_daily <- progress |> 
    filter(!status %in% c("Sin cambio", "Archivado")) |> 
    mutate(
        fecha = as.Date(time_reported),
        status = fct(status, statuses)
    ) |> 
    count(fecha, status, .drop = FALSE) |> 
    mutate(n = na_if(n, 0))

expand_grid(fecha = all_dates, status = statuses) |> 
    left_join(progress_daily) |> 
    group_by(status) |> 
    fill(n) |> 
    ggplot(aes(fecha, n)) +
    geom_area(aes(fill = status)) +
    scale_fill_discrete(limits = statuses, type = RColorBrewer::brewer.pal(6, "Set2"))
```


